apiVersion: v1
kind: ConfigMap
metadata:
  name: config-domain
  namespace: knative-serving
data:
  dev.wa.darknex.us: |
    selector:
      environment: development
  staging.wa.darknex.us: |
    selector:
      environment: staging
  wa.darknex.us: |
    selector:
      environment: production
  autocreate-cluster-domain-claims: "true"
