apiVersion: v1
kind: ConfigMap
metadata:
  name: config-domain
  namespace: knative-serving
data:
  dev.${BASE_DOMAIN}: |
    selector:
      environment: development
  staging.${BASE_DOMAIN}: |
    selector:
      environment: staging
  ${BASE_DOMAIN}: |
    selector:
      environment: production
  autocreate-cluster-domain-claims: "true"
