apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: game-2048-dev-nginx-cert
  namespace: default
spec:
  secretName: game-2048-dev-nginx-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - "${DEV_DOMAIN}"

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: game-2048-staging-nginx-cert
  namespace: default
spec:
  secretName: game-2048-staging-nginx-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - "${STAGING_DOMAIN}"

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: game-2048-prod-nginx-cert
  namespace: default
spec:
  secretName: game-2048-prod-nginx-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - "${PROD_DOMAIN}"
