apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@hndrx.co
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx
    - http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: game-2048-dev-cert
  namespace: knative-serving
spec:
  secretName: game-2048-dev-cert-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - "2048-dev.wa.darknex.us"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: game-2048-staging-cert
  namespace: knative-serving
spec:
  secretName: game-2048-staging-cert-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - "2048-staging.wa.darknex.us"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: game-2048-prod-cert
  namespace: knative-serving
spec:
  secretName: game-2048-prod-cert-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - "2048.wa.darknex.us"
