apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: game-2048-dev
  namespace: game-2048-dev
  labels:
    app: game-2048
    environment: development
  annotations:
    # Scale to zero configuration
    autoscaling.knative.dev/minScale: "0"
    autoscaling.knative.dev/maxScale: "10"
    # Scale down to zero after 30 seconds of no traffic
    autoscaling.knative.dev/scaleDownDelay: "30s"
    # Target concurrency per pod
    autoscaling.knative.dev/target: "100"
spec:
  template:
    metadata:
      labels:
        app: game-2048
        environment: development
      annotations:
        # Scale to zero configuration
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
        autoscaling.knative.dev/scaleDownDelay: "30s"
        autoscaling.knative.dev/target: "100"
    spec:
      containers:
      - name: game-2048
        image: ghcr.io/ghndrx/k8s-game-2048:latest
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: ENVIRONMENT
          value: "development"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
  traffic:
  - percent: 100
    latestRevision: true
